Closes Issue #53
mssiegel/frempco-server pull request #10
Opened 2022-03-01 12:12 UTC by zachlankton

Closes Issue https://github.com/mssiegel/frempco-client/issues/53

Related Front End PR: https://github.com/mssiegel/frempco-client/pull/55

2022-03-01 12:20 UTC, zachlankton commented on services/socketIOSetup.js
> +      if (teacher) deleteClassroom(teacher);
This change was required due to changes made in PR https://github.com/mssiegel/frempco-server/pull/9#discussion_r816717887

2022-03-01 12:20 UTC, zachlankton commented on services/database.js
> +  })
Originally I did `socket.broadcast.emit('teacher left')`  But was not sure if this would broadcast to all teachers and students in other rooms that should not receive that message.  So I did this to double check that the students receiving this message belong to the chat.  There may be a better way, but not sure of one right now.

2022-03-03 04:06 UTC, mssiegel requested changes
So amazing  you found that bug in deleteClassroom!!!!!!!

2022-03-03 04:06 UTC, mssiegel commented on services/database.js
> +  })
We can remove the changes to `deleteClassroom` as we will not be telling students if a teacher left.

2022-03-03 04:06 UTC, mssiegel commented on services/socketIOSetup.js
> +    socket.on('user disconnected', userDisconnected);
We are removing the `'user disconnected'` event. So need to change this code.

2022-03-03 04:06 UTC, mssiegel commented on services/socketIOSetup.js
> +      if (teacher) deleteClassroom(teacher);
Amazing catch!!!! If a teacher tried to deactivate the classroom, the old `deleteClassroom(classroomName, socket.id)` would have caused the backend server to crash from an `unabled to read from "undefined" error`.   From my email, Ariella said that when she deactivated the classroom and reactivated it, the students couldn't login again.  This was the bug!!! Since Heroku crashed, it would have been still restarting when she clicked "activate classroom".  Great catch!!!

2022-03-03 11:57 UTC, merged