Closes #88 Enable typescript on server
mssiegel/frempco-server pull request #14
Opened 2022-03-11 17:40 UTC by karlrez

Closes https://github.com/mssiegel/frempco-client/issues/88

Installed TypeScript, types, and added a tsconfig. No changes to any existing code. 

tsconfig warning for 'no inputs' goes away once you add a TypeScript file to the project
![image](https://user-images.githubusercontent.com/47090434/157919238-ce5ed8ed-1226-44a4-9928-2aed50e2688b.png)

2022-03-11 19:04 UTC, zachlankton requested changes
Good start, but we need to go a little further to setup typescript:

I've made some comments on the tsconfig.json that I think we should address.

We should add `/build` to our `.gitignore` file.

And we will need to make the following changes to our scripts in `package.json`

```json
 "scripts": {
    "dev": "nodemon -e ts --exec \"npm run dev:build\"",
    "start": "node build/index",
    "build": "tsc",
    "dev:build": "tsc && node build/index"
  },
```

We will need the `npm run build` step for Heroku to build the project before starting it with `npm start`.  @mssiegel is this something that you need to do in Heroku before we merge into main? (or dev if you get that setup)?

These script changes will point node to the build version and allow us to develop using the typescript compiler while still using nodemon to watch for changes and run the server.

Also, I think it safe to rename the following files to typescript (*.ts)

```bash
/index.js
/routes/classrooms.js
/services/corsOptions.js
/services/database.js
/services/socketIOSetup.js
```

2022-03-11 23:21 UTC, karlrez commented on tsconfig.json
> +}
Good point, It would be good to be consistent

2022-03-11 23:42 UTC, karlrez commented
Thanks for the review @zachlankton, that was a very good explanation on the setup. I just made my updates as per your comments.

2022-03-13 17:03 UTC, mssiegel approved these changes
Great work addressing Zach's suggestions! I added new comments. Once they're addressed this can be merged!! Heroku should make it work automatically. 
I had suggestions for further typescript improvements but didn't want to block this PR so I made a [new issue](https://github.com/mssiegel/frempco-client/issues/89) for them. 

@karlrez To be extra safe, I'd like to merge this PR.  Once you address the comments, tag me and I'll go ahead and merge and then verify it works in production. 

Also, I am new to Typescript configurations. So feel free to argue back on anything I said!

2022-03-13 17:05 UTC, mssiegel commented on package.json
> +    "dev:build": "tsc && node build/index"
`postinstall` tells Heroku what to do after installing the npm packages
```suggestion
    "dev:build": "tsc && node build/index",
    "postinstall": "tsc"
```

Also, add a new file to the root directory called Procfile and put in `web: node build/index.js`
This tells Heroku the entry point of our app as documented [here](https://medium.com/developer-rants/deploying-typescript-node-js-applications-to-heroku-81dd75424ce0)

2022-03-13 18:49 UTC, mssiegel requested changes
Whoops. I accidentally clicked the button to re-request a review from myself.

2022-03-13 21:01 UTC, karlrez commented on tsconfig.json
> +    "moduleResolution": "node",
After running `npm dev:build` i ran into this:

![image](https://user-images.githubusercontent.com/47090434/158078931-1bb6d0b3-83a5-473f-87fe-b7e41ea8c50d.png)

Updated TypeScript to this version, which resolved the issue:
![image](https://user-images.githubusercontent.com/47090434/158079038-bd10a429-0cea-45ed-bf64-74f09a9a3e42.png)

Let me know if this works for you and I'll merge

2022-03-13 21:14 UTC, mssiegel approved these changes
Looks great! I'm going to merge!

2022-03-13 21:16 UTC, mssiegel requested changes
Don't merge yet. Just saw karls comment

2022-03-13 21:18 UTC, mssiegel commented on tsconfig.json
> +    "moduleResolution": "node",
@karlrez lets change it back to just `"node"`.  I don't know what the whole dev typescript version is and not worth spending the time to look into it.

2022-03-13 21:30 UTC, karlrez commented on tsconfig.json
> +    "moduleResolution": "node",
@mssiegel done, switched back to "node". 
The whole -dev typescript thing was auto generated when I updated, I dont think its required, it also works fine with just the version number

2022-03-14 01:07 UTC, mssiegel commented on tsconfig.json
> +    "moduleResolution": "node",
Thanks for changing it back. Anything that says 'X' is unstable isn't worth us using : )

2022-03-14 01:11 UTC, mssiegel approved these changes
Great work! Normally the person who makes the PR merges. But I'm going to merge this PR so that I can immediately verify it'll work on Heroku.

2022-03-14 01:12 UTC, merged

2022-03-14 01:25 UTC, mssiegel commented
WHOOHOO!!! It works perfectly on production! GREAT TEAM EFFORT EVERYONE!! Getting the backend to use Typescript is a huge step forward!!!