added types.ts and type for classroom
mssiegel/frempco-server pull request #29
Opened 2022-06-18 02:10 UTC by karlrez

resovolves [#136](https://github.com/mssiegel/frempco-client/issues/136)

Added types.ts file and type for classrooms object.

Just a few questions on this:
- Any suggestions on the location of `types.ts` file? 
- Do you have a preferences on using a type instead of interface? 
- In the classroom type I put the name as:  `classroomName: string` . We can be even more explicit and only allow values from our [classrooms list](https://github.com/mssiegel/frempco-client/blob/1c2ab49c01a04a459555be71b28a124b8452ad14/data/classrooms.json). Would this be preferred?

2022-06-19 21:03 UTC, mssiegel requested changes
Thanks for doing this!
 Lets put the `types.ts` file under `services/`. Because its just holding types for `/database.ts` file.

Interfaces are used for objects.  Types are used for single fields. 

Using `classroomName: string` is perfect! Explicitly only allowing names from the client file would be too complex and not worth it.

2022-06-21 03:36 UTC, karlrez commented
Thanks for your feedback! I've added types for the rest of the objects and made the changes requested from the comments. 

One thing I noticed is the chat id's are in the format : `<SocketId>#<SocketId>` . I typed this as a string since typing as socket is a bit misleading. 

I could also add the type as a template literal:
![image](https://user-images.githubusercontent.com/47090434/174710163-af1df5e7-715a-475d-82e1-c600dbdd5773.png)

but this requires later asserting this type later on when we assign the chatId.

2022-06-22 02:52 UTC, mssiegel requested changes
Thanks this is great!
I think using the template literal of `type ChatId = '${SocketId}#${SocketId}';` is a great idea!
You'd then assert on line 106 of `database.ts` `const chatId = (student1.socket.id + '#' + student2.socket.id) as ChatId;`
And would add the ChatId type to the parameters of `deleteChat()` and `unpairStudentChat()`

2022-06-22 02:52 UTC, mssiegel commented on services/types.ts
> +  [classroomName: SocketId]: {
```suggestion
  [classroomName: string]: {
```

2022-06-22 02:52 UTC, mssiegel commented on services/types.ts
> +}
Let's also export Student as its own interface. That way it can be used as a type in the functions `deleteChat()` and `remStudentFromClassroom()`

```suggestion
export interface Students {
  [studentSocketId: SocketId]: Student;
}

export interface Student {
  socket: Socket;
  classroomName: string;
  realName: string;
  peerSocketId: SocketId | null;
}
```

2022-06-23 23:23 UTC, karlrez commented
Good idea exporting Student to its own interface. I've added the changes from your comments.

2022-06-24 02:58 UTC, mssiegel approved these changes
Thanks for tackling this last issue for our codebase! I left one very minor comment to simplify the assertion of `ChatId`. Go ahead and merge.

2022-06-24 02:58 UTC, mssiegel commented on services/database.ts
> +    const chatId = (student1.socket.id + '#' + student2.socket.id) as ChatId;
This is super minor. I think its cleaner without the parenthesis. 
```suggestion
    const chatId = `${student1.socket.id}#${student2.socket.id}` as ChatId;
```

2022-06-24 03:48 UTC, merged